### ISSUE TITLE
When using the mod, Blocks fail to update

### ISSUE THREAD

**Issue by SomeRandomCreatorOrSomthing** [CoolMineman/BitsAndChisels#104]
Here, I am attempting to use the chisel on a Grass Block, as such it does not render properly.

![2022-03-05_08 32 23](https://user-images.githubusercontent.com/100965076/156829625-54c2b7a5-78e6-459e-b0e9-113bc14855da.png)

Please get back to me as soon as possible.

**Comment by CoolMineman** [comment]
please read the FAQ on sodium
you need to remove sodium or add indium
