### ISSUE TITLE
[Bug] Break on dedicated server

### ISSUE THREAD

**Issue by Oliver-makes-code** [CoolMineman/BitsAndChisels#109]
Investigation of this doesn't lead to any conclusions, so I'll leave it here

Mods: https://pastebin.com/EvixVUzM
Video showcasing:
https://cdn.discordapp.com/attachments/957930008054202410/959975689652666438/2022-04-02_17-27-26_Trim.mp4

**Comment by williambl** [comment]
The video seems to just be a static image of a discord channel

**Comment by Oliver-makes-code** [comment]
> The video seems to just be a static image of a discord channel

Fixed
