### ISSUE TITLE
Chisel Blocks turning invisible

### ISSUE THREAD

**Issue by CottonCandyBoi** [CoolMineman/BitsAndChisels#113]
didn't have this problem as all until I added sodium, now any block that's been chiseled turns completely invisible, all the empty spots are where chiseled blocks are, and i had a pot made out of bits on the smoker that you cant see
![2022-04-07_22 01 02](https://user-images.githubusercontent.com/82586406/162354638-5838c3fb-8b8d-474b-82e4-3a15406eeaf6.png)

**Comment by ThatGeekyWeeb** [comment]
been having this same issue, also using sodium

seems to fix itself something if you hope between the nether and overworld

**Comment by d-Pixie** [comment]
@CottonCandyBoi @ThatGeekyWeeb Have you also installed Indium? You will need that for Sodium to use Fabrics renderer correctly. I had the same problem before I found that out ...

**Comment by ThatGeekyWeeb** [comment]
I actually seem to still be having the issue with Indium added and enabled

**Comment by CoolMineman** [comment]
update latest version
