### ISSUE TITLE
Blocks created with blueprint invisible.

### ISSUE THREAD

**Issue by d-Pixie** [CoolMineman/BitsAndChisels#114]
I have problems with creating blocks from blueprints. Whenever I try this (except once, no idea why it worked that time) I get an empty bits block, but the bits are deducted from my inventory. It's invisible, has a full-block hitbox, and casts a shadow.

If I restart the server or change dimension it disappears from rendering. Some residual effects - like placing a normal block where one of the bit blocks was, before they disappeared, and it also disappearing - makes me think that there might still be something in that block space though.

I'm using MultiMC on the client-side with these mods:
```
BitsAndChisels 2.6.7
Carpet Extra 1.4.64
Carpet Mod 1.4.66
Carpet-AutoCraftingTable 1.4.56
Fabric Loader 0.13.3
Fabric-API 0.48.0+1.18.2
Indium 1.0.2+mc1.18.2
Litematica 0.11.1
Lithium 0.7.9
MaLiLib 0.12.1
MiniHUD 0.22.0
Phosphor 0.8.1
Replay Mod 1.18.2-2.6.4
Sodium 0.4.1+build.15
Tweakeroo 0.13.1
Waystones 10.0.0
WorldEdit 7.2.10+1742f98
WorldEditCUI 1.18.2+01
```
Against a 1.18.2 fabric server with these mods:
```
bitsandchisels-2.6.7.jar
carpet-autocraftingtable-1.18-1.4.56.jar
carpet-extra-1.18.2-pre2-1.4.64.jar
fabric-api-0.48.0+1.18.2.jar
fabric-carpet-1.18.2-1.4.68+v220324.jar
indium-1.0.2 mc1.18.2
lithium-fabric-mc1.18.2-0.7.9.jar
phosphor-fabric-mc1.18.x-0.8.1.jar
servux-fabric-1.18.2-0.1.0.jar
sodium-fabric-mc1.18.2-0.4.1+build.15.jar
waystones-fabric-1.18.2-10.0.0
```

![2022-04-09_15 36 41](https://user-images.githubusercontent.com/1247102/162575282-d89fb009-a0c6-4383-880f-fd2227af698f.png)

**Comment by d-Pixie** [comment]
To simplify the debugging a bit @CoolMineman I pared my plugins down to:
```
BitsAndChisels 2.6.7
Fabric Loader 0.13.3
Fabric-API 0.48.0+1.18.2
Indium 1.0.2+mc1.18.2
Lithium 0.7.9
Phosphor 0.8.1
Sodium 0.4.1+build.15
```
and tried it in single-player, but I have the same problem.

Let me know if you need help debugging on my side. I'm a dev - although not primarily in Java - so I can probably do whatever you need 🙂

**Comment by d-Pixie** [comment]
This also appears to happen when you place a single bit on top of a block. The bit is invisible and instead, I get one of the full invisible blocks.

I also noticed, by pure chance, that I can get the "hidden" invisible blocks to appear again. I used an item from another mod and it made them pop into existence again.

**Comment by CoolMineman** [comment]
2.6.8
