### ISSUE TITLE
Textures get mirrored on edit

### ISSUE THREAD

**Issue by d-Pixie** [CoolMineman/BitsAndChisels#116]
If I try and edit a stone bricks block the texture gets mirrored as soon as I cut a bit from it. The wrench only rotates the mesh, not the texture, and since it is mirrored and not rotated it wouldn't help anyway, unfortunately...

![2022-04-09_21 06 46](https://user-images.githubusercontent.com/1247102/162702032-c37f28c7-794b-4146-9dec-c0776d548573.png)
![2022-04-09_21 06 53](https://user-images.githubusercontent.com/1247102/162702050-ccb18bf7-7487-4aaf-8c05-3300c3f27eb2.png)

**Comment by CoolMineman** [comment]
dupe #23
