### ISSUE TITLE
Top texture of chiseled block mirrored along z axis

### ISSUE THREAD

**Issue by Oliver-makes-code** [CoolMineman/BitsAndChisels#129]
![2022-08-01_19 59 46](https://user-images.githubusercontent.com/59418903/182269455-543cac3e-7e0e-4373-bcfa-774bf4a119f0.png)

**Comment by Whitebrim** [comment]
Bump, this still is present:
![2023-07-21_06 43 38](https://github.com/CoolMineman/BitsAndChisels/assets/23287829/5df16950-0459-4658-91ad-8551fc0b5b60)
(Bit collection block in the middle has mirrored texture along blue (z) axis)

**Comment by Whitebrim** [comment]
Fixed in 2.7.3
