### ISSUE TITLE
Server crash when starting the game

### ISSUE THREAD

**Issue by vinnyg0621** [CoolMineman/BitsAndChisels#13]
[here is the log](https://pastebin.com/8dYRCxF8)

**Comment by CoolMineman** [comment]
Some combination of Stacc (Library used by mod), Optifabric/Optifine, and Fabrication is causing this crash. If it works by removing Fabrication report it to Fabrication's GitHub. If it works by removing Optifabric and Optifine report it to Optifabric's GitHub.

**Comment by vinnyg0621** [comment]
it still crashes even without Fabrication
