### ISSUE TITLE
needs bumping to mc 1.19.2, mod loaders don't recognise it as compatible

### ISSUE THREAD

**Issue by netcore10** [CoolMineman/BitsAndChisels#134]

**Comment by CoolMineman** [comment]
? https://github.com/CoolMineman/BitsAndChisels/blob/master/src/main/resources/fabric.mod.json#L39

**Comment by netcore10** [comment]
mod manager's don't show the mod as 1.19.2 compatable

**Comment by netcore10** [comment]
could just be an error on my specific one.
