### ISSUE TITLE
Inventorio compatibility, infinite stacks bug.

### ISSUE THREAD

**Issue by dehen** [CoolMineman/BitsAndChisels#140]
Love both these mods, posting this report [to both](https://github.com/Lizard-Of-Oz/Inventorio/issues/190) because I don't know which side owns it.

There's a weird interaction between the way [Inventorio](https://www.curseforge.com/minecraft/mc-mods/inventorio) is handling pickups, and [BitsAndChisels](https://www.curseforge.com/minecraft/mc-mods/bits-and-chisels) is handling large stacks of bits. Basically, if Inventorio has a full stack of something in one of the offhand slots, or in a Deep Pocket slot and then picks up another drop of it, you can push your stack beyond 64. I made a 32k stack of sticks, lol.

The minimum modstack to trigger this seems to be:
Fabric API
Fabric Language Kotlin (inventorio dependency)
Inventorio
BitsAndChisels

Reproduction steps:
single player cheats on
give yourself 128 sticks
put a stack in your Inventorio offhand
throw the other stack on the ground
pick it up
128 sticks

This feels like an Inventorio issue initially, but doesn't happen if BitsAndChisels is off. Likewise, it can't be reproduced with the Vanilla offhand, with Inventorio off. So it appears to be an interaction.

1.19.2/Fabric 14.10

**Comment by mastery3** [comment]
Reproduced this bug in Survival mode

**Comment by mastery3** [comment]
Same bug in Stacker, a seperate mod. This may be caused by a library used by both

**Comment by mastery3** [comment]
Weird stuff going on with Stacker; the bug can only stack to the highest amount a different (or the same, but that wouldn't be a bug) item can stack to. May be the same thing going on here, since the bits seem to stack infinitely.
https://github.com/Andrew6rant/Stacker/issues/70

**Comment by mastery3** [comment]
Reproduced the bug with only Inventorio and it's dependencies.

**Comment by dehen** [comment]
Closing this bug on this side. It's become clear this is an Inventorio issue that Bits just makes more obvious. Thanks for the investigation
