### ISSUE TITLE
Bits and chisels breaking waterlogged block causes server crash and timeout 1.19.2

### ISSUE THREAD

**Issue by netcore10** [CoolMineman/BitsAndChisels#141]
[server crash.txt](https://github.com/CoolMineman/BitsAndChisels/files/9955537/server.crash.txt)
[2022-11-07-7.log](https://github.com/CoolMineman/BitsAndChisels/files/9955539/2022-11-07-7.log)

**Comment by netcore10** [comment]
https://mclo.gs/UCf9YIR

**Comment by CoolMineman** [comment]
c2me is doing something strange

**Comment by netcore10** [comment]
it still crashes without c2me. https://mclo.gs/kxtjBLh

**Comment by netcore10** [comment]
theres a weird index out of bounds issue with your mod.

**Comment by netcore10** [comment]
This seems to be server side only too, works in singleplayer.
