### ISSUE TITLE
Cannot load plugin–jar does not contain Plugin.yml

### ISSUE THREAD

**Issue by joeyfigaro** [CoolMineman/BitsAndChisels#142]
![image](https://user-images.githubusercontent.com/1386477/202748039-59c960df-5d04-4d86-bc9a-648fca256402.png)

Running into this issue on a [Nodecraft](https://nodecraft.com) server running Paper 1.17* and Bits & Chisels 2.6.0. Any insight?

**Comment by CoolMineman** [comment]
This mod is for the fabric mod loader and will not load on a paper server. This mod fundamentally cannot exist on a paper server.
