### ISSUE TITLE
Visual glitch when chiseling green blocks.

### ISSUE THREAD

**Issue by morganofthefairies** [CoolMineman/BitsAndChisels#149]
I'm not sure if this extends to other blocks as well but the only blocks that I have experienced this with is grass, green concrete powder, and green concrete. ![image](https://user-images.githubusercontent.com/96499111/211285872-99d51dd5-aaa0-4c64-b05b-2b8301b9946d.png)![image](https://user-images.githubusercontent.com/96499111/211285892-44d97945-cb64-4a23-83d5-b9cea3ba7d1b.png) I have changed shaders, turned them off completely, but neither seemed to work.

**Comment by CoolMineman** [comment]
this is an old bug in sodium
