### ISSUE TITLE
[Feature Request] Enable placing down more bits

### ISSUE THREAD

**Issue by Noaaan** [CoolMineman/BitsAndChisels#16]
This mod is great. I have experimented with it on my server using mods such as Origins Extended with players picking the Inchling race, which makes the player a quarter of their size, and they fit perfectly inside buildings using bits and chisels!

For some of the larger projects my players have raised their annoyances of having to place down absolutely everything pixel by pixel. A new tool, or something similar, which could enable placing down more bits to save time would be ideal. 
I think the most efficient ones would be 2x2x2, 4x4x4, or something configurable.

Keep on making cool stuff!

**Comment by Kuggle01** [comment]
I hate the same thought, glad I'm not alone here, time can be saved a bit by making the wall or whatever you want for that block and then copying it with a blueprint, but a bits builders wand or even just the ability to place bits in a radius like you said would go a long way

**Comment by ImUrX** [comment]
@CoolMineman do you have an idea on how this is gonna be? make a bit builder wand of differenty qualities? I'm thinking of making a PR :p

**Comment by CoolMineman** [comment]
Shifting with bits to place in a region added in 2.5.4
