### ISSUE TITLE
Badly Compressed Packets

### ISSUE THREAD

**Issue by Symbolicaly** [CoolMineman/BitsAndChisels#2]
I downloaded the mod again after the update that fixed the dedicated server crash and this time im getting a badly compressed packets error.

**Comment by CoolMineman** [comment]
Please post your log

**Comment by Symbolicaly** [comment]
[latest.log](https://github.com/CoolMineman/BitsAndChisels/files/5574665/latest.log)

**Comment by CoolMineman** [comment]
please post a log where the badly compressed packets error occurs

**Comment by Symbolicaly** [comment]
I downloaded the 1.1.4 version and still getting the same error. Thats the only log that generated, the server didnt crash so I cant post the crash log.

**Comment by CoolMineman** [comment]
Sorry meant #6 in that commit

**Comment by CoolMineman** [comment]
sorry for late response could you try with this mod? [https://www.curseforge.com/minecraft/mc-mods/xl-packets-fabric](https://www.curseforge.com/minecraft/mc-mods/xl-packets-fabric)

**Comment by Neubulae** [comment]
After countless hours of debugging with NO PROPER LOG OUTPUT I finally located this mod as the source of the weird `Lost Connection` issue.
Simply summarize(?), if there are TOO MANY BLOCKS REGISTERED(conjecture) this mod will simply yeet myself out of server, but for whatever reason, NO ACTUAL REPORT PRODUCES. I'm greeted with this:
![1W3EU7O{9C7%ZSZ_~4TVKVD](https://user-images.githubusercontent.com/24774842/105223138-5721ff80-5b96-11eb-9549-d6fbb566fb4c.png)
I urge you to companion this into your mod, i.e. JiJing or simply fix this, I was tormented for a week y'know.
