### ISSUE TITLE
Invisible blocks

### ISSUE THREAD

**Issue by sphnxs** [CoolMineman/BitsAndChisels#28]
the blocks go invisible when I use a chisel on them, any solutions?

**Comment by CoolMineman** [comment]
Update to the latest version and if it still happens send your log

**Comment by LapisLuked** [comment]
I'm on the most recent version and I have this problem aswell.

**Comment by CoolMineman** [comment]
Remove sodium or use sodium/next with indium.

**Comment by rmortes** [comment]
Iris' Integrated sodium may be randomly making chiseled blocks go invisible / making their hitbox go full block. Is this related?
