### ISSUE TITLE
Deleting issue

### ISSUE THREAD

**Issue by wildrocket16** [CoolMineman/BitsAndChisels#36]
hello, your probably not going to read this but if you are I need to say, I love this mod and it's really good and I like to use it with pehkui and such. but there's a thing when using the chisel blocks you cant break it with your fist or it all disappears... like say for, I was making a barn house for my tiny dog, and *poof* it went away cause I accidentally used my fist and broke the so-called "whole block". I don't know if there is any way to fix this like with a undo or like something but it's kinda annoying when you trying to make something and then it all goes away. I hope there maybe is a way you can fix this but I don't know if this is. thank you for listening.

**Comment by CoolMineman** [comment]
When you break the whole block it should drop the whole block
