### ISSUE TITLE
Add GoldChisel and WoodChisel. I made them for you already.

### ISSUE THREAD

**Issue by True-cc** [CoolMineman/BitsAndChisels#37]
I already made the chisels for you in my mod. I'll remove them when you add them.
![image](https://user-images.githubusercontent.com/38010540/112735990-a117c080-8f0c-11eb-924c-09d856a412e8.png)
https://github.com/True-cc/BuilderHelper/
https://github.com/True-cc/BuilderHelper/tree/master/src/main/java/uwu/smsgamer/builderhelper/compat/chitsAndBisels/items

Edit: Gold is 2x2 and Wood is 8x8. I didn't add any crafting recipes for them though.

**Comment by rmortes** [comment]
It's a good idea! Maybe try to make a pull request with your changes and crafting recipes?

**Comment by CoolMineman** [comment]
decided against this
