### ISSUE TITLE
Make the custom blocks pushable via pistons pliz.

### ISSUE THREAD

**Issue by True-cc** [CoolMineman/BitsAndChisels#38]
Make the custom blocks pushable via pistons pliz.
Edit: if it's even possible. I'm sure it is but u might need to do fancy mixin shenanigans

**Comment by CoolMineman** [comment]
out of scope, other mods such as carpet allow pushable block entities

**Comment by True-cc** [comment]
ok. figured as much once I realised they were block entities.
