### ISSUE TITLE
Game Crashes When Bits and Chisels is intsalled.

### ISSUE THREAD

**Issue by BulletDash10** [CoolMineman/BitsAndChisels#40]
Hello, I have been wanting to use this mod for a while, so i downloaded it! However when placed in the mod folder, the game does not open. Rather is loads than immediately crashes. Attached is an image of my mods folder incase it is needed.
![image](https://user-images.githubusercontent.com/79344670/113549016-f30ac580-9633-11eb-977f-7039e6e442c9.png)

**Comment by CoolMineman** [comment]
optifine is not supported
