### ISSUE TITLE
sodium with indium and BitsAndChisels get crash

### ISSUE THREAD

**Issue by O-Oski** [CoolMineman/BitsAndChisels#41]
hello when I try to enter my server I get a crash report and I have already add this mods to my server except sodium and indium ... should I add indium to my server. 
the Error
[crash-2021-04-06_15.30.24-client.txt](https://github.com/CoolMineman/BitsAndChisels/files/6264724/crash-2021-04-06_15.30.24-client.txt)

The game crashed whilst unexpected error
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
Exit Code: -1

**Comment by fukoff-bitch** [comment]
i have the same problem :/

**Comment by PurpleGamer** [comment]
Yeah, after installing and putting both mods in the mod folder with bits and chisels, it crashes for me too

**Comment by Matthew-MBG** [comment]
Has NO ONE seen this?????

**Comment by CoolMineman** [comment]
See comp500/Indium#57
