### ISSUE TITLE
Crash whenever stepping on chiseled blocks

### ISSUE THREAD

**Issue by MoonRoroos** [CoolMineman/BitsAndChisels#47]
I play on a server with some friends, and this doesn't seem to affect them, and we're all using the same mods, but whenever I step on a chiseled block, no matter what, my game instantly crashes for no reason. We're using origins, industrial revolution, and tech reborn mainly for mods, but this doesn't seem to happen to anyone else.

**Comment by CoolMineman** [comment]
Make sure to update to the latest version and post your log if it still happens on the latest version

**Comment by CoolMineman** [comment]
likely same as #57 reopen with log it it's a separate issue
