### ISSUE TITLE
Game crashed while I chiseled a block

### ISSUE THREAD

**Issue by qsefthuopq** [CoolMineman/BitsAndChisels#5]
Running on Fabric 1.16.3
Crash report:
https://pastebin.com/Z278ynzS

**Comment by CoolMineman** [comment]
try updating fabric api [https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3049067](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3049067)
