### ISSUE TITLE
I'm going insane!

### ISSUE THREAD

**Issue by ZiggietheGreat** [CoolMineman/BitsAndChisels#50]
I'm going absolutely nuts rebuilding blocks and creating the same thing I just created over and over again. Please, make a reconstructor type item. You left-click a block you want to copy, if you have the bits in your inventory, you can copy it with a right-click. That's my idea anyway. I just need _something_ to make this copying and reconstructing process faster.
Edit: Just thought of the chance for different modes on such a tool. I realize I'm talking about potentially completely new programming (I can nearly even begin to read the code used for chrome) but this would be a really useful tool.

**Comment by cozyGalvinism** [comment]
You can already do that... Craft a blueprint, rightclick your build, rightclick somewhere else and it'll try and reconstruct the block from the ground up (meaning if you don't have enough bits, it will look unfinished)

**Comment by ZiggietheGreat** [comment]
So... I'm playing on a modded server and didn't realize the blueprint I found was part of the same mod. I'll just see myself out, thanks.

**Comment by FourInchKnife** [comment]
> So... I'm playing on a modded server and didn't realize the blueprint I found was part of the same mod. I'll just see myself out, thanks.

Before you do, please close the issue :)

**Comment by CoolMineman** [comment]
Hopefully you are fine now
