### ISSUE TITLE
Corrupted Chunks

### ISSUE THREAD

**Issue by ArcticBeverage** [CoolMineman/BitsAndChisels#51]
I enjoy the mod very much, but when I playin creative if I make something using too many 'chiseled' blocks it corrupts the chunks it is in, freezing my character if within the chunk and not loading the chunk correctly. I am unsure of the exact problem that is causing the issue. For more information I do use the blueprints quite a lot as it helps speed the building process up and I have the Corrupted file and the back-up file of a world I have been working on, I have lost a few worlds and may hours to this.
![2021-05-12_20 17 08](https://user-images.githubusercontent.com/84108593/118060547-fd219180-b360-11eb-9cbc-2a58cb805225.png)
![2021-05-12_20 21 37](https://user-images.githubusercontent.com/84108593/118060560-03b00900-b361-11eb-821c-8570c02a18b2.png)

**Comment by CoolMineman** [comment]
I'm thinking this might be because of the high nbt size

**Comment by CoolMineman** [comment]
Unable to reproduce, can you send both worlds and the mod list?

**Comment by ArcticBeverage** [comment]
[SW Corrupted.zip](https://github.com/CoolMineman/BitsAndChisels/files/6481593/SW.Corrupted.zip)
[SW Working Backup.zip](https://github.com/CoolMineman/BitsAndChisels/files/6481594/SW.Working.Backup.zip)
[mods.zip](https://github.com/CoolMineman/BitsAndChisels/files/6481596/mods.zip)

Here are the corrupted and working worlds and my mods.

**Comment by CoolMineman** [comment]
I was able to load the chunks after removing immersive portals
![2021-05-14_22 30 23](https://user-images.githubusercontent.com/62723322/118346808-a7d1b580-b503-11eb-9d79-abba682a5336.png)

**Comment by CoolMineman** [comment]
This issue seems to not be present in immersive portals 0.9 (your version is 0.8)
