### ISSUE TITLE
Attempting to push a bit block with a piston causes the server to crash

### ISSUE THREAD

**Issue by Maxmani** [CoolMineman/BitsAndChisels#58]
As long as the chunk is loaded the server will keep crashing until the piston is removed e.g. by resetting the chunk.
The crash report:
> ---- Minecraft Crash Report ----
> // You're mean.
> 
> Time: 5/26/21, 3:52 PM
> Description: Ticking block entity
> 
> java.lang.ClassCastException: class net.minecraft.class_2669 cannot be cast to class io.github.coolmineman.bitsandchisels.BitsBlockEntity (net.minecraft.class_2669 and io.github.coolmineman.bitsandchisels.BitsBlockEntity are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @5117dd67)
> 	at io.github.coolmineman.bitsandchisels.BitsBlock.method_9530(BitsBlock.java:53)
> 	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:786)
> 	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:782)
> 	at net.minecraft.class_4970.method_9549(class_4970.java:324)
> 	at net.minecraft.class_4970$class_4971.handler$cgb000$phaseThroughBlocks(class_4970.java:3577)
> 	at net.minecraft.class_4970$class_4971.method_26194(class_4970.java)
> 	at net.minecraft.class_4970$class_4971.method_26220(class_4970.java:793)
> 	at net.minecraft.class_2669.method_11503(class_2669.java:113)
> 	at net.minecraft.class_2669.method_16896(class_2669.java:329)
> 	at net.minecraft.class_1937.method_18471(class_1937.java:510)
> 	at net.minecraft.class_3218.method_18765(class_3218.java:429)
> 	at net.minecraft.server.MinecraftServer.redirect$bcl000$ficUpdateSuppressionCrashTick(MinecraftServer.java:3707)
> 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
> 	at net.minecraft.class_3176.method_3813(class_3176.java:312)
> 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
> 	at net.minecraft.server.MinecraftServer.handler$bpo000$modifiedRunLoop(MinecraftServer.java:6810)
> 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:651)
> 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Server thread
> Stacktrace:
> 	at io.github.coolmineman.bitsandchisels.BitsBlock.method_9530(BitsBlock.java:53)
> 	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:786)
> 	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:782)
> 	at net.minecraft.class_4970.method_9549(class_4970.java:324)
> 	at net.minecraft.class_4970$class_4971.handler$cgb000$phaseThroughBlocks(class_4970.java:3577)
> 	at net.minecraft.class_4970$class_4971.method_26194(class_4970.java)
> 	at net.minecraft.class_4970$class_4971.method_26220(class_4970.java:793)
> 	at net.minecraft.class_2669.method_11503(class_2669.java:113)
> 	at net.minecraft.class_2669.method_16896(class_2669.java:329)
> 
> -- Block entity being ticked --
> Details:
> 	Name: minecraft:piston // net.minecraft.class_2669
> 	Block: Block{minecraft:moving_piston}[facing=down,type=normal]
> 	Block location: World: (234,70,38), Chunk: (at 10,4,6 in 14,2; contains blocks 224,0,32 to 239,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
> 	Block: Block{minecraft:moving_piston}[facing=down,type=normal]
> 	Block location: World: (234,70,38), Chunk: (at 10,4,6 in 14,2; contains blocks 224,0,32 to 239,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
> Stacktrace:
> 	at net.minecraft.class_1937.method_18471(class_1937.java:510)
> 	at net.minecraft.class_3218.method_18765(class_3218.java:429)
> 	at net.minecraft.server.MinecraftServer.redirect$bcl000$ficUpdateSuppressionCrashTick(MinecraftServer.java:3707)
> 
> -- Affected level --
> Details:
> 	All players: 1 total; [class_3222['Maxmani'/66, l='ServerLevel[world]', x=232.37, y=71.00, z=36.84]]
> 	Chunk stats: ServerChunkCache: 3600
> 	Level dimension: minecraft:overworld
> 	Level spawn location: World: (-244,96,-206), Chunk: (at 12,6,2 in -16,-13; contains blocks -256,0,-208 to -241,255,-193), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
> 	Level time: 19529190 game time, 19814641 day time
> 	Level name: world
> 	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
> 	Level weather: Rain time: 61015 (now: false), thunder time: 114209 (now: false)
> 	Known server brands: fabric
> 	Level was modded: true
> 	Level storage version: 0x04ABD - Anvil
> Stacktrace:
> 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
> 	at net.minecraft.class_3176.method_3813(class_3176.java:312)
> 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
> 	at net.minecraft.server.MinecraftServer.handler$bpo000$modifiedRunLoop(MinecraftServer.java:6810)
> 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:651)
> 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.16.5
> 	Minecraft Version ID: 1.16.5
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 11.0.10, AdoptOpenJDK
> 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
> 	Memory: 1599110144 bytes (1525 MB) / 4294967296 bytes (4096 MB) up to 6442450944 bytes (6144 MB)
> 	CPUs: 12
> 	JVM Flags: 2 total; -Xms4096m -Xmx6144m
> 	Fabric Mods: 
> 		adventure-platform-fabric: adventure-platform-fabric 4.0.0-SNAPSHOT
> 		appleskin: AppleSkin 1.0.11
> 		autoconfig1u: Auto Config v1 Updated 3.3.1
> 		autoconfigtoml: AutoConfig-TOML 1.0.0-fabric
> 		bedrockwaters: BedrockWaters 1.4.3+1.16.4
> 		bedspreads: Bedspreads 1.3.1-1.16.4
> 		bitsandchisels: BitsAndChisels 2.2.0
> 		brokennametags: Broken Name Tags 1.0.1
> 		cardinal-components: Cardinal Components API 2.8.2
> 		cardinal-components-base: Cardinal Components API (base) 2.8.2
> 		cardinal-components-block: Cardinal Components API (blocks) 2.8.2
> 		cardinal-components-chunk: Cardinal Components API (chunks) 2.8.2
> 		cardinal-components-entity: Cardinal Components API (entities) 2.8.2
> 		cardinal-components-item: Cardinal Components API (items) 2.8.2
> 		cardinal-components-level: Cardinal Components API (world saves) 2.8.2
> 		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.2
> 		cardinal-components-util: Cardinal Components API (utilities) 2.8.2
> 		cardinal-components-world: Cardinal Components API (worlds) 2.8.2
> 		carpet: Carpet Mod 1.4.35
> 		carpet-extra: Carpet Extra 1.4.34
> 		cauldronconcrete: Cauldron Concrete 1.0.0+1.16.5-fabric
> 		cleancut: CleanCut mc1.16-2.1-fabric
> 		cloth-basic-math: Cloth Basic Math 0.5.1
> 		cloth-client-events-v0: Cloth Client Events v0 1.5.47
> 		cloth-config2: Cloth Config v4 4.11.24
> 		com_electronwill_night-config_core: core 3.6.3
> 		com_electronwill_night-config_toml: toml 3.6.3
> 		com_github_ben-manes_caffeine_caffeine: caffeine 2.8.0
> 		com_graphql-java_graphql-java: graphql-java 16.1
> 		com_graphql-java_java-dataloader: java-dataloader 2.2.3
> 		com_zaxxer_hikaricp: HikariCP 3.4.2
> 		couplings: Couplings 1.3.3
> 		creativeonepunch: Creative One-Punch 1.1
> 		deltalogger: DeltaLogger 1.1.3
> 		extraorigins: Extra Origins 1.16.5-11
> 		fabric: Fabric API 0.34.2+1.16
> 		fabric-api-base: Fabric API Base 0.3.0+c88702897d
> 		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
> 		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
> 		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
> 		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
> 		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
> 		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
> 		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
> 		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
> 		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
> 		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
> 		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
> 		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
> 		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
> 		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
> 		fabric-language-kotlin: Fabric Language Kotlin 1.6.0+kotlin.1.5.0
> 		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
> 		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
> 		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
> 		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
> 		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
> 		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
> 		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
> 		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
> 		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
> 		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
> 		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
> 		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
> 		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
> 		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
> 		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
> 		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
> 		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
> 		fabrication: Fabrication 1.3.4
> 		fabriccrossdimtpfix: FabricCrossDimTPFix 0.1.0
> 		fabricloader: Fabric Loader 0.11.3
> 		fallflyinglib: FallFlyingLib 1.1.0
> 		ferritecore: FerriteCore 2.0.4
> 		flora-doubling: Flora Doubling 1.3.0+1.16.4-fabric
> 		harvest: Harvest 1.2.12
> 		invview: InvView 1.4.1-1.16.4+
> 		io_leangen_geantyref_geantyref: geantyref 1.3.7
> 		itemflexer: ItemFlexer 1.1.4
> 		java: OpenJDK 64-Bit Server VM 11
> 		keepheadnames: Keep Head Names 1.2
> 		krypton: Krypton 0.1.2
> 		lapisreserve: Lapis Reserve 1.0.6
> 		leaf-decay: Leaf Decay 1.2.0-1.16.1
> 		lithium: Lithium 0.6.4
> 		microconfig: Microconfig 1.1.0
> 		minecraft: Minecraft 1.16.5
> 		minimotd-fabric: MiniMOTD 2.0.2
> 		moborigins: Mob Origins 1.4.0
> 		monster-in-the-closet: Monsters in the Closet 1.0.0
> 		mysql_mysql-connector-java: mysql-connector-java 8.0.19
> 		nbtcrafting: NBT Crafting 2.0.11+mc1.16.4
> 		net_kyori_adventure-api: adventure-api 4.7.0
> 		net_kyori_adventure-key: adventure-key 4.7.0
> 		net_kyori_adventure-platform-api: adventure-platform-api 4.0.0-SNAPSHOT
> 		net_kyori_adventure-text-feature-pagination: adventure-text-feature-pagination 4.0.0-SNAPSHOT
> 		net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.1.0-SNAPSHOT
> 		net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.7.0
> 		net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.7.0
> 		net_kyori_examination-api: examination-api 1.1.0
> 		net_kyori_examination-string: examination-string 1.1.0
> 		onsoulfire: On Soul Fire 1.16.5-2
> 		org_antlr_antlr4-runtime: antlr4-runtime 4.7.2
> 		org_apache_logging_log4j_log4j-slf4j-impl: log4j-slf4j-impl 2.8.1
> 		org_jdbi_jdbi3-core: jdbi3-core 3.12.2
> 		org_jdbi_jdbi3-sqlite: jdbi3-sqlite 3.12.2
> 		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.0
> 		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.0
> 		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.0
> 		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.0
> 		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0-RC
> 		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0-RC
> 		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.0
> 		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.0
> 		org_reactivestreams_reactive-streams: reactive-streams 1.0.3
> 		org_slf4j_slf4j-api: slf4j-api 1.8.0-beta4
> 		org_xerial_sqlite-jdbc: sqlite-jdbc 3.32.3.2
> 		origins: Origins 0.7.1
> 		origins-classes: Origins: Classes 1.1.1
> 		originsplus: Origins Plus 0.0.2
> 		overworld_two: Overworld 2 1.0.4
> 		packet_tweaker: Packet Tweaker 0.1.1
> 		pehkui: Pehkui 2.1.0+21w18a
> 		perplayerspawns: Example Mod 1.16.4-1.0.0
> 		pride: Pride Lib 1.0.0+1.16
> 		proper_mobcap_modifier: Proper Mobcap Modifier 1.0
> 		pvptoggle: Pvp Toggle 1.0.3
> 		randompatches: RandomPatches 2.4.5-fabric
> 		reach-entity-attributes: Reach Entity Attributes 1.1.1
> 		recipecache: recipecache 0.1.0
> 		roughlyenoughitems: Roughly Enough Items 5.11.218
> 		roughlyenoughitems-api: REI (API) 5.11.218
> 		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.218
> 		roughlyenoughitems-runtime: REI (Runtime) 5.11.218
> 		server_translations_api: Server Translations API 1.4.0
> 		sign_editor: Better Signs & Frames mc-1.16.5-0.7.0
> 		sit: Sit 1.16.5-11
> 		spark: spark 1.5.2
> 		stacc: Stacc 1.0.1
> 		starlight: Starlight fabric-1.0.0-RC2-82ae5ca
> 		strawdummy: Straw Dummy 1.4.0
> 		tweed: Tweed API 3.0.0-beta.22
> 		unlimiteddragoneggs: Unlimited Dragon Eggs 1.1.1
> 		voicechat: Simple Voice Chat 1.16.5-1.3.10
> 		wandering_collector: Wandering Collector 1.0.1+mc1.16.5
> 		wither_cage_fix: Wither Cage Fix 1.0.6+MC1.16.1-1.16.5
> 		xlpackets: XLPackets 1.1
> 	Player Count: 1 / 50; [class_3222['Maxmani'/66, l='ServerLevel[world]', x=232.37, y=71.00, z=36.84]]
> 	Data Packs: vanilla (incompatible), Fabric Mods, file/DisableOrigins.zip, file/TouhouOrigins, file/bac_advancements
> 	Is Modded: Definitely; Server brand changed to 'fabric'
> 	Type: Dedicated Server (map_server.txt)

**Comment by CoolMineman** [comment]
update b&c
