### ISSUE TITLE
Whether to consider compatibility with Velocity？

### ISSUE THREAD

**Issue by WangJiangJiaoZi** [CoolMineman/BitsAndChisels#66]
crossstitch: v0.1.4
velocity: v1.1.8
minecraft: v1.16.5
BitsAndChisels: v2.3.2

Unable to enter the game after using this mod. Would you consider compatibility?

**Comment by CoolMineman** [comment]
if it doesn't work after 2.5.2 (removed xl packets) then there's not much I can do
