### ISSUE TITLE
Crash Upon Start with v2.5.2

### ISSUE THREAD

**Issue by emoace** [CoolMineman/BitsAndChisels#75]
Attached is a crash report: [crash-2021-07-26_23.23.09-client.txt](https://github.com/CoolMineman/BitsAndChisels/files/6882661/crash-2021-07-26_23.23.09-client.txt)

This seems to prevent MC from starting no matter what mods I disable that it says is causing the crash, for instance, this one mentions "AdventureZ"

It seems that v2.5.0 works fine though.

**Comment by CoolMineman** [comment]
fixed in 2.5.3
