### ISSUE TITLE
Chisel does not respect claimed blocks [1.17.1]

### ISSUE THREAD

**Issue by red2blue** [CoolMineman/BitsAndChisels#81]
Using FLAN as claim management system, the Chisels do not respect claimed areas and anyone can start chipping away someone else's blocks.

**Comment by red2blue** [comment]
I am not the mod author?????????

**Comment by orlouge** [comment]
Bits can still be placed in claimed areas after the last commit, both on new blocks and inside existing chiseled blocks.

**Comment by Sebas-Re** [comment]
This issue is still happening on latest 1.18.2 version of the Mod, and it doesn't seems to have been fixed on 1.19 either by looking at the changelogs...
