### ISSUE TITLE
wont open server 

### ISSUE THREAD

**Issue by ghostlyGremlin** [CoolMineman/BitsAndChisels#84]
im on an Origins mod server with some friends and we recently added bits and chisels to the pack for the Inchlings. ive troubleshooted on my end multiple times, but i cant get onto the server due to the error listed in the attached screenshot. i dont know enough about mods to know what sort of solution i should even be looking for so any help would be hugely appreciated
[![b+c error msg](https://user-images.githubusercontent.com/93059245/138573472-33df7143-ea60-465d-b045-79c3be663c7a.JPG)
d.](url)

**Comment by Cats1595** [comment]
I have the mod both on the server and in my mods folder and i keep getting the same message. Any fixes?
