### ISSUE TITLE
Visual render bug

### ISSUE THREAD

**Issue by theflashgirl20** [CoolMineman/BitsAndChisels#85]
The chiselled blocks turn invisible on a server after teleporting somewhere than back. Teleporting someone else to the location of the chiselled blocks fixes it

**Comment by red2blue** [comment]
same thing happens on Another quality modpack 2

**Comment by serioos** [comment]
Same here. Except it turn invisible for me the moment I use the chisel on the block.

**Comment by serioos** [comment]
Mine was resolved when I installed Indium since I had installed Sodium too.

**Comment by CoolMineman** [comment]
should be fixed in the 1.18 versions
