### ISSUE TITLE
Simple Iron Chisel should break bits smaller than 4x4

### ISSUE THREAD

**Issue by comp500** [CoolMineman/BitsAndChisels#9]
It'd be really annoying to place a single bit, then only be able to get it back as a Bit Collection Block without making a Simple Diamond Chisel. I presume more complex chisels (that can break in different shapes?) are also planned in the future?

**Comment by CoolMineman** [comment]
You can still break the 4x4x4 the single bit is in with the iron chisel

**Comment by comp500** [comment]
Doesn't look like it to me, am I doing something wrong?

https://user-images.githubusercontent.com/1138417/105804994-f846f680-5f98-11eb-8f9a-0602a4bfec64.mp4
