### ISSUE TITLE
Is there any know performance issues on servers? Noticed TPS was High and Saw this.

### ISSUE THREAD

**Issue by KaneHart** [CoolMineman/BitsAndChisels#90]
I might be reading it wrong using spark profile

![image](https://user-images.githubusercontent.com/425853/147496510-8ba4b4f6-481d-428e-827e-36e3622cc8cb.png)

**Comment by KaneHart** [comment]
I can confirm it's a real issue.

https://spark.lucko.me/DxZcMxT7E6

It looks like it's the Saving of the NBT data? Not 100% sure...

Examples of just boring old tps...

Before VV logsout:
![image](https://user-images.githubusercontent.com/425853/147501062-e7d49bf6-5cf4-4929-ac03-14f8d2c90ec8.png)

VV Loggedout:
![image](https://user-images.githubusercontent.com/425853/147501084-90c5bcb4-2b8a-4faf-bce3-0797ce586020.png)

VV Logged Back in:
![image](https://user-images.githubusercontent.com/425853/147501135-61f2e204-ce6c-49de-9e4b-60c37105d3d2.png)


These were a a bunch seconds + before and after to count for spikes.

**Comment by Dolphin2Point1** [comment]
I think this is just an issue with having a huge amount of bit blocks in a small area. I don't know what can be done in code other than just optimizing the function to save the NBT. The only thing I could think of doing that could make a dent is stop using indexof which wouldn't really help unless you have a lot of different types of bits in one block, but looking at the spark link you sent I don't think you do.

**Comment by KaneHart** [comment]
I will let the person who created all the bits explain what he had done with his base.

**Comment by vvenaya** [comment]
All bits have been removed from my base now. Sadly i do believe this mod is not ready to be used on multiplayer servers.  If these issues arise with just one person using these blocks, what would happen if 10+ players start doing the same ?

**Comment by Dolphin2Point1** [comment]
I mean, that's kind of like asking what would happen when lots of people spam chunk loaders. Personally, I don't think that many people will get to that level of usage, however I feel like it's not really that easy to optimize. I would still like to know how exactly you got the times so high to see if anything can be done about it.

**Comment by CoolMineman** [comment]
In a sane world chunk unloading would not block the main tick loop. Not sure what else there is to say, my code there is decently optimized and optimizing TACS is out of scope of this mod.

**Comment by CoolMineman** [comment]
@KaneHart try the new version https://cdn.modrinth.com/data/q8MC5tW2/versions/2.6.4/bitsandchisels-2.6.4.jar
