### ISSUE TITLE
Multiplayer in Creative Mode bug

### ISSUE THREAD

**Issue by kuri10923** [CoolMineman/BitsAndChisels#95]
use smart chisel to left click any block, the block will disappear
use diamond and iron chisel to left click any block, the block will become a cut block
environment : 1.18.1 fabric 0.12.12 and bits and chisels 2.6.1 to 2.6.3
![2021-12-29_23 10 52](https://user-images.githubusercontent.com/96833028/147678275-798d7ee2-8585-46ad-8d1e-238916f49357.png)

**Comment by BaeyDesola** [comment]
have the same problem
bitsandchisels-2.6.4
